/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'soldListings' : bigint,
  'activeListings' : bigint,
  'totalListings' : bigint,
  'totalInquiries' : bigint,
}
export type ExternalBlob = Uint8Array;
export type FacingDirection = { 'southEast' : null } |
  { 'southWest' : null } |
  { 'east' : null } |
  { 'west' : null } |
  { 'northEast' : null } |
  { 'northWest' : null } |
  { 'south' : null } |
  { 'north' : null };
export type InquiryId = bigint;
export interface InquiryInput {
  'name' : string,
  'propertyId' : PropertyId,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface InquiryPublic {
  'id' : InquiryId,
  'name' : string,
  'createdAt' : Timestamp,
  'propertyId' : PropertyId,
  'isRead' : boolean,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface MonthlyInquiryCount { 'month' : string, 'count' : bigint }
export interface PropertyFilter {
  'featured' : [] | [boolean],
  'propertyType' : [] | [PropertyType],
  'minSize' : [] | [bigint],
  'city' : [] | [string],
  'sold' : [] | [boolean],
  'maxPrice' : [] | [bigint],
  'minPrice' : [] | [bigint],
  'maxSize' : [] | [bigint],
  'facing' : [] | [FacingDirection],
}
export type PropertyId = bigint;
export interface PropertyInput {
  'title' : string,
  'featured' : boolean,
  'propertyType' : PropertyType,
  'city' : string,
  'description' : string,
  'amenities' : Array<string>,
  'price' : bigint,
  'facing' : FacingDirection,
  'sizeSqft' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface PropertyPublic {
  'id' : PropertyId,
  'title' : string,
  'featured' : boolean,
  'propertyType' : PropertyType,
  'listerId' : Principal,
  'city' : string,
  'published' : boolean,
  'createdAt' : Timestamp,
  'sold' : boolean,
  'description' : string,
  'amenities' : Array<string>,
  'viewCount' : bigint,
  'price' : bigint,
  'facing' : FacingDirection,
  'sizeSqft' : bigint,
  'images' : Array<ExternalBlob>,
}
export type PropertyType = { 'studio' : null } |
  { 'commercial' : null } |
  { 'other' : null } |
  { 'villa' : null } |
  { 'flat' : null } |
  { 'penthouse' : null } |
  { 'plot' : null } |
  { 'townhouse' : null };
export interface PropertyViewCount {
  'title' : string,
  'propertyId' : PropertyId,
  'viewCount' : bigint,
}
export type Timestamp = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VisitRequestId = bigint;
export interface VisitRequestInput {
  'name' : string,
  'propertyId' : PropertyId,
  'email' : string,
  'message' : string,
  'preferredDate' : string,
  'preferredTime' : string,
  'phone' : string,
}
export interface VisitRequestPublic {
  'id' : VisitRequestId,
  'status' : VisitStatus,
  'customerPrincipal' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'propertyId' : PropertyId,
  'email' : string,
  'message' : string,
  'preferredDate' : string,
  'preferredTime' : string,
  'phone' : string,
}
export type VisitStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'reviewed' : null } |
  { 'confirmed' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addBookmark' : ActorMethod<[PropertyId], undefined>,
  'addProperty' : ActorMethod<[PropertyInput], PropertyPublic>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProperty' : ActorMethod<[PropertyId], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerDashboard' : ActorMethod<[], { 'bookmarkCount' : bigint }>,
  'getEmployeeDashboard' : ActorMethod<
    [],
    {
      'monthlyInquiries' : Array<MonthlyInquiryCount>,
      'stats' : DashboardStats,
      'topPropertyViews' : Array<PropertyViewCount>,
    }
  >,
  'getInquiry' : ActorMethod<[InquiryId], [] | [InquiryPublic]>,
  'getProperty' : ActorMethod<[PropertyId], [] | [PropertyPublic]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listBookmarks' : ActorMethod<[], Array<PropertyId>>,
  'listEmployeeProperties' : ActorMethod<[], Array<PropertyPublic>>,
  'listInquiries' : ActorMethod<[], Array<InquiryPublic>>,
  'listInquiriesForProperty' : ActorMethod<[PropertyId], Array<InquiryPublic>>,
  'listProperties' : ActorMethod<[PropertyFilter], Array<PropertyPublic>>,
  'listVisitRequests' : ActorMethod<[], Array<VisitRequestPublic>>,
  'listVisitRequestsForCustomer' : ActorMethod<[], Array<VisitRequestPublic>>,
  'markInquiryRead' : ActorMethod<[InquiryId], boolean>,
  'markPropertySold' : ActorMethod<[PropertyId, boolean], boolean>,
  'publishProperty' : ActorMethod<
    [PropertyId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removeBookmark' : ActorMethod<[PropertyId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitInquiry' : ActorMethod<[InquiryInput], InquiryPublic>,
  'submitVisitRequest' : ActorMethod<[VisitRequestInput], VisitRequestPublic>,
  'unpublishProperty' : ActorMethod<
    [PropertyId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateProperty' : ActorMethod<
    [PropertyId, PropertyInput],
    [] | [PropertyPublic]
  >,
  'updateVisitRequestStatus' : ActorMethod<
    [VisitRequestId, VisitStatus],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];