/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PropertyId = IDL.Nat;
export const PropertyType = IDL.Variant({
  'studio' : IDL.Null,
  'commercial' : IDL.Null,
  'other' : IDL.Null,
  'villa' : IDL.Null,
  'flat' : IDL.Null,
  'penthouse' : IDL.Null,
  'plot' : IDL.Null,
  'townhouse' : IDL.Null,
});
export const FacingDirection = IDL.Variant({
  'southEast' : IDL.Null,
  'southWest' : IDL.Null,
  'east' : IDL.Null,
  'west' : IDL.Null,
  'northEast' : IDL.Null,
  'northWest' : IDL.Null,
  'south' : IDL.Null,
  'north' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PropertyInput = IDL.Record({
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'propertyType' : PropertyType,
  'city' : IDL.Text,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
  'facing' : FacingDirection,
  'sizeSqft' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const Timestamp = IDL.Int;
export const PropertyPublic = IDL.Record({
  'id' : PropertyId,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'propertyType' : PropertyType,
  'listerId' : IDL.Principal,
  'city' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : Timestamp,
  'sold' : IDL.Bool,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'viewCount' : IDL.Nat,
  'price' : IDL.Nat,
  'facing' : FacingDirection,
  'sizeSqft' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const MonthlyInquiryCount = IDL.Record({
  'month' : IDL.Text,
  'count' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'soldListings' : IDL.Nat,
  'activeListings' : IDL.Nat,
  'totalListings' : IDL.Nat,
  'totalInquiries' : IDL.Nat,
});
export const PropertyViewCount = IDL.Record({
  'title' : IDL.Text,
  'propertyId' : PropertyId,
  'viewCount' : IDL.Nat,
});
export const InquiryId = IDL.Nat;
export const InquiryPublic = IDL.Record({
  'id' : InquiryId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'propertyId' : PropertyId,
  'isRead' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const PropertyFilter = IDL.Record({
  'featured' : IDL.Opt(IDL.Bool),
  'propertyType' : IDL.Opt(PropertyType),
  'minSize' : IDL.Opt(IDL.Nat),
  'city' : IDL.Opt(IDL.Text),
  'sold' : IDL.Opt(IDL.Bool),
  'maxPrice' : IDL.Opt(IDL.Nat),
  'minPrice' : IDL.Opt(IDL.Nat),
  'maxSize' : IDL.Opt(IDL.Nat),
  'facing' : IDL.Opt(FacingDirection),
});
export const VisitRequestId = IDL.Nat;
export const VisitStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'reviewed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const VisitRequestPublic = IDL.Record({
  'id' : VisitRequestId,
  'status' : VisitStatus,
  'customerPrincipal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'propertyId' : PropertyId,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'preferredTime' : IDL.Text,
  'phone' : IDL.Text,
});
export const InquiryInput = IDL.Record({
  'name' : IDL.Text,
  'propertyId' : PropertyId,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const VisitRequestInput = IDL.Record({
  'name' : IDL.Text,
  'propertyId' : PropertyId,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'preferredTime' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addBookmark' : IDL.Func([PropertyId], [], []),
  'addProperty' : IDL.Func([PropertyInput], [PropertyPublic], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProperty' : IDL.Func([PropertyId], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerDashboard' : IDL.Func(
      [],
      [IDL.Record({ 'bookmarkCount' : IDL.Nat })],
      ['query'],
    ),
  'getEmployeeDashboard' : IDL.Func(
      [],
      [
        IDL.Record({
          'monthlyInquiries' : IDL.Vec(MonthlyInquiryCount),
          'stats' : DashboardStats,
          'topPropertyViews' : IDL.Vec(PropertyViewCount),
        }),
      ],
      ['query'],
    ),
  'getInquiry' : IDL.Func([InquiryId], [IDL.Opt(InquiryPublic)], ['query']),
  'getProperty' : IDL.Func([PropertyId], [IDL.Opt(PropertyPublic)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBookmarks' : IDL.Func([], [IDL.Vec(PropertyId)], ['query']),
  'listEmployeeProperties' : IDL.Func([], [IDL.Vec(PropertyPublic)], ['query']),
  'listInquiries' : IDL.Func([], [IDL.Vec(InquiryPublic)], ['query']),
  'listInquiriesForProperty' : IDL.Func(
      [PropertyId],
      [IDL.Vec(InquiryPublic)],
      ['query'],
    ),
  'listProperties' : IDL.Func(
      [PropertyFilter],
      [IDL.Vec(PropertyPublic)],
      ['query'],
    ),
  'listVisitRequests' : IDL.Func([], [IDL.Vec(VisitRequestPublic)], ['query']),
  'listVisitRequestsForCustomer' : IDL.Func(
      [],
      [IDL.Vec(VisitRequestPublic)],
      ['query'],
    ),
  'markInquiryRead' : IDL.Func([InquiryId], [IDL.Bool], []),
  'markPropertySold' : IDL.Func([PropertyId, IDL.Bool], [IDL.Bool], []),
  'publishProperty' : IDL.Func(
      [PropertyId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removeBookmark' : IDL.Func([PropertyId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitInquiry' : IDL.Func([InquiryInput], [InquiryPublic], []),
  'submitVisitRequest' : IDL.Func(
      [VisitRequestInput],
      [VisitRequestPublic],
      [],
    ),
  'unpublishProperty' : IDL.Func(
      [PropertyId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateProperty' : IDL.Func(
      [PropertyId, PropertyInput],
      [IDL.Opt(PropertyPublic)],
      [],
    ),
  'updateVisitRequestStatus' : IDL.Func(
      [VisitRequestId, VisitStatus],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PropertyId = IDL.Nat;
  const PropertyType = IDL.Variant({
    'studio' : IDL.Null,
    'commercial' : IDL.Null,
    'other' : IDL.Null,
    'villa' : IDL.Null,
    'flat' : IDL.Null,
    'penthouse' : IDL.Null,
    'plot' : IDL.Null,
    'townhouse' : IDL.Null,
  });
  const FacingDirection = IDL.Variant({
    'southEast' : IDL.Null,
    'southWest' : IDL.Null,
    'east' : IDL.Null,
    'west' : IDL.Null,
    'northEast' : IDL.Null,
    'northWest' : IDL.Null,
    'south' : IDL.Null,
    'north' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PropertyInput = IDL.Record({
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'propertyType' : PropertyType,
    'city' : IDL.Text,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
    'facing' : FacingDirection,
    'sizeSqft' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Timestamp = IDL.Int;
  const PropertyPublic = IDL.Record({
    'id' : PropertyId,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'propertyType' : PropertyType,
    'listerId' : IDL.Principal,
    'city' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : Timestamp,
    'sold' : IDL.Bool,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'viewCount' : IDL.Nat,
    'price' : IDL.Nat,
    'facing' : FacingDirection,
    'sizeSqft' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const MonthlyInquiryCount = IDL.Record({
    'month' : IDL.Text,
    'count' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'soldListings' : IDL.Nat,
    'activeListings' : IDL.Nat,
    'totalListings' : IDL.Nat,
    'totalInquiries' : IDL.Nat,
  });
  const PropertyViewCount = IDL.Record({
    'title' : IDL.Text,
    'propertyId' : PropertyId,
    'viewCount' : IDL.Nat,
  });
  const InquiryId = IDL.Nat;
  const InquiryPublic = IDL.Record({
    'id' : InquiryId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'propertyId' : PropertyId,
    'isRead' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PropertyFilter = IDL.Record({
    'featured' : IDL.Opt(IDL.Bool),
    'propertyType' : IDL.Opt(PropertyType),
    'minSize' : IDL.Opt(IDL.Nat),
    'city' : IDL.Opt(IDL.Text),
    'sold' : IDL.Opt(IDL.Bool),
    'maxPrice' : IDL.Opt(IDL.Nat),
    'minPrice' : IDL.Opt(IDL.Nat),
    'maxSize' : IDL.Opt(IDL.Nat),
    'facing' : IDL.Opt(FacingDirection),
  });
  const VisitRequestId = IDL.Nat;
  const VisitStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'reviewed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const VisitRequestPublic = IDL.Record({
    'id' : VisitRequestId,
    'status' : VisitStatus,
    'customerPrincipal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'propertyId' : PropertyId,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'preferredTime' : IDL.Text,
    'phone' : IDL.Text,
  });
  const InquiryInput = IDL.Record({
    'name' : IDL.Text,
    'propertyId' : PropertyId,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const VisitRequestInput = IDL.Record({
    'name' : IDL.Text,
    'propertyId' : PropertyId,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'preferredTime' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addBookmark' : IDL.Func([PropertyId], [], []),
    'addProperty' : IDL.Func([PropertyInput], [PropertyPublic], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProperty' : IDL.Func([PropertyId], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerDashboard' : IDL.Func(
        [],
        [IDL.Record({ 'bookmarkCount' : IDL.Nat })],
        ['query'],
      ),
    'getEmployeeDashboard' : IDL.Func(
        [],
        [
          IDL.Record({
            'monthlyInquiries' : IDL.Vec(MonthlyInquiryCount),
            'stats' : DashboardStats,
            'topPropertyViews' : IDL.Vec(PropertyViewCount),
          }),
        ],
        ['query'],
      ),
    'getInquiry' : IDL.Func([InquiryId], [IDL.Opt(InquiryPublic)], ['query']),
    'getProperty' : IDL.Func([PropertyId], [IDL.Opt(PropertyPublic)], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBookmarks' : IDL.Func([], [IDL.Vec(PropertyId)], ['query']),
    'listEmployeeProperties' : IDL.Func(
        [],
        [IDL.Vec(PropertyPublic)],
        ['query'],
      ),
    'listInquiries' : IDL.Func([], [IDL.Vec(InquiryPublic)], ['query']),
    'listInquiriesForProperty' : IDL.Func(
        [PropertyId],
        [IDL.Vec(InquiryPublic)],
        ['query'],
      ),
    'listProperties' : IDL.Func(
        [PropertyFilter],
        [IDL.Vec(PropertyPublic)],
        ['query'],
      ),
    'listVisitRequests' : IDL.Func(
        [],
        [IDL.Vec(VisitRequestPublic)],
        ['query'],
      ),
    'listVisitRequestsForCustomer' : IDL.Func(
        [],
        [IDL.Vec(VisitRequestPublic)],
        ['query'],
      ),
    'markInquiryRead' : IDL.Func([InquiryId], [IDL.Bool], []),
    'markPropertySold' : IDL.Func([PropertyId, IDL.Bool], [IDL.Bool], []),
    'publishProperty' : IDL.Func(
        [PropertyId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removeBookmark' : IDL.Func([PropertyId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitInquiry' : IDL.Func([InquiryInput], [InquiryPublic], []),
    'submitVisitRequest' : IDL.Func(
        [VisitRequestInput],
        [VisitRequestPublic],
        [],
      ),
    'unpublishProperty' : IDL.Func(
        [PropertyId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateProperty' : IDL.Func(
        [PropertyId, PropertyInput],
        [IDL.Opt(PropertyPublic)],
        [],
      ),
    'updateVisitRequestStatus' : IDL.Func(
        [VisitRequestId, VisitStatus],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };