/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PropertyFilter {
    featured?: boolean;
    propertyType?: PropertyType;
    minSize?: bigint;
    city?: string;
    sold?: boolean;
    maxPrice?: bigint;
    minPrice?: bigint;
    maxSize?: bigint;
    facing?: FacingDirection;
}
export interface VisitRequestPublic {
    id: VisitRequestId;
    status: VisitStatus;
    customerPrincipal: Principal;
    name: string;
    createdAt: Timestamp;
    propertyId: PropertyId;
    email: string;
    message: string;
    preferredDate: string;
    preferredTime: string;
    phone: string;
}
export type VisitRequestId = bigint;
export type Timestamp = bigint;
export interface MonthlyInquiryCount {
    month: string;
    count: bigint;
}
export interface InquiryPublic {
    id: InquiryId;
    name: string;
    createdAt: Timestamp;
    propertyId: PropertyId;
    isRead: boolean;
    email: string;
    message: string;
    phone: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface InquiryInput {
    name: string;
    propertyId: PropertyId;
    email: string;
    message: string;
    phone: string;
}
export interface DashboardStats {
    soldListings: bigint;
    activeListings: bigint;
    totalListings: bigint;
    totalInquiries: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface PropertyPublic {
    id: PropertyId;
    title: string;
    featured: boolean;
    propertyType: PropertyType;
    listerId: Principal;
    city: string;
    published: boolean;
    createdAt: Timestamp;
    sold: boolean;
    description: string;
    amenities: Array<string>;
    viewCount: bigint;
    price: bigint;
    facing: FacingDirection;
    sizeSqft: bigint;
    images: Array<ExternalBlob>;
}
export interface VisitRequestInput {
    name: string;
    propertyId: PropertyId;
    email: string;
    message: string;
    preferredDate: string;
    preferredTime: string;
    phone: string;
}
export interface PropertyInput {
    title: string;
    featured: boolean;
    propertyType: PropertyType;
    city: string;
    description: string;
    amenities: Array<string>;
    price: bigint;
    facing: FacingDirection;
    sizeSqft: bigint;
    images: Array<ExternalBlob>;
}
export type InquiryId = bigint;
export type PropertyId = bigint;
export interface PropertyViewCount {
    title: string;
    propertyId: PropertyId;
    viewCount: bigint;
}
export interface UserProfile {
    name: string;
    role: string;
}
export enum FacingDirection {
    southEast = "southEast",
    southWest = "southWest",
    east = "east",
    west = "west",
    northEast = "northEast",
    northWest = "northWest",
    south = "south",
    north = "north"
}
export enum PropertyType {
    studio = "studio",
    commercial = "commercial",
    other = "other",
    villa = "villa",
    flat = "flat",
    penthouse = "penthouse",
    plot = "plot",
    townhouse = "townhouse"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VisitStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    reviewed = "reviewed",
    confirmed = "confirmed"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addBookmark(propertyId: PropertyId): Promise<void>;
    addProperty(input: PropertyInput): Promise<PropertyPublic>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteProperty(id: PropertyId): Promise<boolean>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomerDashboard(): Promise<{
        bookmarkCount: bigint;
    }>;
    getEmployeeDashboard(): Promise<{
        monthlyInquiries: Array<MonthlyInquiryCount>;
        stats: DashboardStats;
        topPropertyViews: Array<PropertyViewCount>;
    }>;
    getInquiry(id: InquiryId): Promise<InquiryPublic | null>;
    getProperty(id: PropertyId): Promise<PropertyPublic | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listBookmarks(): Promise<Array<PropertyId>>;
    listEmployeeProperties(): Promise<Array<PropertyPublic>>;
    listInquiries(): Promise<Array<InquiryPublic>>;
    listInquiriesForProperty(propertyId: PropertyId): Promise<Array<InquiryPublic>>;
    listProperties(filter: PropertyFilter): Promise<Array<PropertyPublic>>;
    listVisitRequests(): Promise<Array<VisitRequestPublic>>;
    listVisitRequestsForCustomer(): Promise<Array<VisitRequestPublic>>;
    markInquiryRead(id: InquiryId): Promise<boolean>;
    markPropertySold(id: PropertyId, sold: boolean): Promise<boolean>;
    publishProperty(id: PropertyId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    removeBookmark(propertyId: PropertyId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitInquiry(input: InquiryInput): Promise<InquiryPublic>;
    submitVisitRequest(input: VisitRequestInput): Promise<VisitRequestPublic>;
    unpublishProperty(id: PropertyId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateProperty(id: PropertyId, input: PropertyInput): Promise<PropertyPublic | null>;
    updateVisitRequestStatus(id: VisitRequestId, status: VisitStatus): Promise<boolean>;
}
import type { ExternalBlob as _ExternalBlob, FacingDirection as _FacingDirection, InquiryPublic as _InquiryPublic, PropertyFilter as _PropertyFilter, PropertyId as _PropertyId, PropertyInput as _PropertyInput, PropertyPublic as _PropertyPublic, PropertyType as _PropertyType, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole, VisitRequestId as _VisitRequestId, VisitRequestPublic as _VisitRequestPublic, VisitStatus as _VisitStatus, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addBookmark(arg0: PropertyId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBookmark(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBookmark(arg0);
            return result;
        }
    }
    async addProperty(arg0: PropertyInput): Promise<PropertyPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.addProperty(await to_candid_PropertyInput_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PropertyPublic_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProperty(await to_candid_PropertyInput_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PropertyPublic_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n24(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n24(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteProperty(arg0: PropertyId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProperty(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerDashboard(): Promise<{
        bookmarkCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerDashboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerDashboard();
            return result;
        }
    }
    async getEmployeeDashboard(): Promise<{
        monthlyInquiries: Array<MonthlyInquiryCount>;
        stats: DashboardStats;
        topPropertyViews: Array<PropertyViewCount>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeDashboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeDashboard();
            return result;
        }
    }
    async getInquiry(arg0: InquiryId): Promise<InquiryPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiry(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiry(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProperty(arg0: PropertyId): Promise<PropertyPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperty(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperty(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listBookmarks(): Promise<Array<PropertyId>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBookmarks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBookmarks();
            return result;
        }
    }
    async listEmployeeProperties(): Promise<Array<PropertyPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEmployeeProperties();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEmployeeProperties();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async listInquiries(): Promise<Array<InquiryPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInquiries();
            return result;
        }
    }
    async listInquiriesForProperty(arg0: PropertyId): Promise<Array<InquiryPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInquiriesForProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInquiriesForProperty(arg0);
            return result;
        }
    }
    async listProperties(arg0: PropertyFilter): Promise<Array<PropertyPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProperties(to_candid_PropertyFilter_n32(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProperties(to_candid_PropertyFilter_n32(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVisitRequests(): Promise<Array<VisitRequestPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVisitRequests();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVisitRequests();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVisitRequestsForCustomer(): Promise<Array<VisitRequestPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVisitRequestsForCustomer();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVisitRequestsForCustomer();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async markInquiryRead(arg0: InquiryId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markInquiryRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markInquiryRead(arg0);
            return result;
        }
    }
    async markPropertySold(arg0: PropertyId, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markPropertySold(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPropertySold(arg0, arg1);
            return result;
        }
    }
    async publishProperty(arg0: PropertyId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.publishProperty(arg0);
                return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishProperty(arg0);
            return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeBookmark(arg0: PropertyId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBookmark(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBookmark(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitInquiry(arg0: InquiryInput): Promise<InquiryPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0);
            return result;
        }
    }
    async submitVisitRequest(arg0: VisitRequestInput): Promise<VisitRequestPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.submitVisitRequest(arg0);
                return from_candid_VisitRequestPublic_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitVisitRequest(arg0);
            return from_candid_VisitRequestPublic_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async unpublishProperty(arg0: PropertyId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.unpublishProperty(arg0);
                return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpublishProperty(arg0);
            return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProperty(arg0: PropertyId, arg1: PropertyInput): Promise<PropertyPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProperty(arg0, await to_candid_PropertyInput_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProperty(arg0, await to_candid_PropertyInput_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateVisitRequestStatus(arg0: VisitRequestId, arg1: VisitStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVisitRequestStatus(arg0, to_candid_VisitStatus_n40(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVisitRequestStatus(arg0, to_candid_VisitStatus_n40(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FacingDirection_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FacingDirection): FacingDirection {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_PropertyPublic_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyPublic): Promise<PropertyPublic> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_VisitRequestPublic_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisitRequestPublic): VisitRequestPublic {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_VisitStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisitStatus): VisitStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InquiryPublic]): InquiryPublic | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PropertyPublic]): Promise<PropertyPublic | null> {
    return value.length === 0 ? null : await from_candid_PropertyPublic_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PropertyId;
    title: string;
    featured: boolean;
    propertyType: _PropertyType;
    listerId: Principal;
    city: string;
    published: boolean;
    createdAt: _Timestamp;
    sold: boolean;
    description: string;
    amenities: Array<string>;
    viewCount: bigint;
    price: bigint;
    facing: _FacingDirection;
    sizeSqft: bigint;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: PropertyId;
    title: string;
    featured: boolean;
    propertyType: PropertyType;
    listerId: Principal;
    city: string;
    published: boolean;
    createdAt: Timestamp;
    sold: boolean;
    description: string;
    amenities: Array<string>;
    viewCount: bigint;
    price: bigint;
    facing: FacingDirection;
    sizeSqft: bigint;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        featured: value.featured,
        propertyType: from_candid_PropertyType_n18(_uploadFile, _downloadFile, value.propertyType),
        listerId: value.listerId,
        city: value.city,
        published: value.published,
        createdAt: value.createdAt,
        sold: value.sold,
        description: value.description,
        amenities: value.amenities,
        viewCount: value.viewCount,
        price: value.price,
        facing: from_candid_FacingDirection_n20(_uploadFile, _downloadFile, value.facing),
        sizeSqft: value.sizeSqft,
        images: await from_candid_vec_n22(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VisitRequestId;
    status: _VisitStatus;
    customerPrincipal: Principal;
    name: string;
    createdAt: _Timestamp;
    propertyId: _PropertyId;
    email: string;
    message: string;
    preferredDate: string;
    preferredTime: string;
    phone: string;
}): {
    id: VisitRequestId;
    status: VisitStatus;
    customerPrincipal: Principal;
    name: string;
    createdAt: Timestamp;
    propertyId: PropertyId;
    email: string;
    message: string;
    preferredDate: string;
    preferredTime: string;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_VisitStatus_n37(_uploadFile, _downloadFile, value.status),
        customerPrincipal: value.customerPrincipal,
        name: value.name,
        createdAt: value.createdAt,
        propertyId: value.propertyId,
        email: value.email,
        message: value.message,
        preferredDate: value.preferredDate,
        preferredTime: value.preferredTime,
        phone: value.phone
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studio: null;
} | {
    commercial: null;
} | {
    other: null;
} | {
    villa: null;
} | {
    flat: null;
} | {
    penthouse: null;
} | {
    plot: null;
} | {
    townhouse: null;
}): PropertyType {
    return "studio" in value ? PropertyType.studio : "commercial" in value ? PropertyType.commercial : "other" in value ? PropertyType.other : "villa" in value ? PropertyType.villa : "flat" in value ? PropertyType.flat : "penthouse" in value ? PropertyType.penthouse : "plot" in value ? PropertyType.plot : "townhouse" in value ? PropertyType.townhouse : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    southEast: null;
} | {
    southWest: null;
} | {
    east: null;
} | {
    west: null;
} | {
    northEast: null;
} | {
    northWest: null;
} | {
    south: null;
} | {
    north: null;
}): FacingDirection {
    return "southEast" in value ? FacingDirection.southEast : "southWest" in value ? FacingDirection.southWest : "east" in value ? FacingDirection.east : "west" in value ? FacingDirection.west : "northEast" in value ? FacingDirection.northEast : "northWest" in value ? FacingDirection.northWest : "south" in value ? FacingDirection.south : "north" in value ? FacingDirection.north : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    reviewed: null;
} | {
    confirmed: null;
}): VisitStatus {
    return "cancelled" in value ? VisitStatus.cancelled : "pending" in value ? VisitStatus.pending : "completed" in value ? VisitStatus.completed : "reviewed" in value ? VisitStatus.reviewed : "confirmed" in value ? VisitStatus.confirmed : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
async function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PropertyPublic>): Promise<Array<PropertyPublic>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PropertyPublic_n16(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VisitRequestPublic>): Array<VisitRequestPublic> {
    return value.map((x)=>from_candid_VisitRequestPublic_n35(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FacingDirection_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FacingDirection): _FacingDirection {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyFilter_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyFilter): _PropertyFilter {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
async function to_candid_PropertyInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyInput): Promise<_PropertyInput> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_VisitStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VisitStatus): _VisitStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    featured?: boolean;
    propertyType?: PropertyType;
    minSize?: bigint;
    city?: string;
    sold?: boolean;
    maxPrice?: bigint;
    minPrice?: bigint;
    maxSize?: bigint;
    facing?: FacingDirection;
}): {
    featured: [] | [boolean];
    propertyType: [] | [_PropertyType];
    minSize: [] | [bigint];
    city: [] | [string];
    sold: [] | [boolean];
    maxPrice: [] | [bigint];
    minPrice: [] | [bigint];
    maxSize: [] | [bigint];
    facing: [] | [_FacingDirection];
} {
    return {
        featured: value.featured ? candid_some(value.featured) : candid_none(),
        propertyType: value.propertyType ? candid_some(to_candid_PropertyType_n10(_uploadFile, _downloadFile, value.propertyType)) : candid_none(),
        minSize: value.minSize ? candid_some(value.minSize) : candid_none(),
        city: value.city ? candid_some(value.city) : candid_none(),
        sold: value.sold ? candid_some(value.sold) : candid_none(),
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none(),
        maxSize: value.maxSize ? candid_some(value.maxSize) : candid_none(),
        facing: value.facing ? candid_some(to_candid_FacingDirection_n12(_uploadFile, _downloadFile, value.facing)) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    featured: boolean;
    propertyType: PropertyType;
    city: string;
    description: string;
    amenities: Array<string>;
    price: bigint;
    facing: FacingDirection;
    sizeSqft: bigint;
    images: Array<ExternalBlob>;
}): Promise<{
    title: string;
    featured: boolean;
    propertyType: _PropertyType;
    city: string;
    description: string;
    amenities: Array<string>;
    price: bigint;
    facing: _FacingDirection;
    sizeSqft: bigint;
    images: Array<_ExternalBlob>;
}> {
    return {
        title: value.title,
        featured: value.featured,
        propertyType: to_candid_PropertyType_n10(_uploadFile, _downloadFile, value.propertyType),
        city: value.city,
        description: value.description,
        amenities: value.amenities,
        price: value.price,
        facing: to_candid_FacingDirection_n12(_uploadFile, _downloadFile, value.facing),
        sizeSqft: value.sizeSqft,
        images: await to_candid_vec_n14(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    studio: null;
} | {
    commercial: null;
} | {
    other: null;
} | {
    villa: null;
} | {
    flat: null;
} | {
    penthouse: null;
} | {
    plot: null;
} | {
    townhouse: null;
} {
    return value == PropertyType.studio ? {
        studio: null
    } : value == PropertyType.commercial ? {
        commercial: null
    } : value == PropertyType.other ? {
        other: null
    } : value == PropertyType.villa ? {
        villa: null
    } : value == PropertyType.flat ? {
        flat: null
    } : value == PropertyType.penthouse ? {
        penthouse: null
    } : value == PropertyType.plot ? {
        plot: null
    } : value == PropertyType.townhouse ? {
        townhouse: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FacingDirection): {
    southEast: null;
} | {
    southWest: null;
} | {
    east: null;
} | {
    west: null;
} | {
    northEast: null;
} | {
    northWest: null;
} | {
    south: null;
} | {
    north: null;
} {
    return value == FacingDirection.southEast ? {
        southEast: null
    } : value == FacingDirection.southWest ? {
        southWest: null
    } : value == FacingDirection.east ? {
        east: null
    } : value == FacingDirection.west ? {
        west: null
    } : value == FacingDirection.northEast ? {
        northEast: null
    } : value == FacingDirection.northWest ? {
        northWest: null
    } : value == FacingDirection.south ? {
        south: null
    } : value == FacingDirection.north ? {
        north: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VisitStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    reviewed: null;
} | {
    confirmed: null;
} {
    return value == VisitStatus.cancelled ? {
        cancelled: null
    } : value == VisitStatus.pending ? {
        pending: null
    } : value == VisitStatus.completed ? {
        completed: null
    } : value == VisitStatus.reviewed ? {
        reviewed: null
    } : value == VisitStatus.confirmed ? {
        confirmed: null
    } : value;
}
async function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
